### ISSUE TITLE
'ClusterManager' object has no attribute 'list_dask_clusters'

### ISSUE THREAD

**Issue by ericdill** [coiled/feedback#17]
@necaris clicking on an individual cluster in this view 
![image](https://user-images.githubusercontent.com/6223243/84265034-2ce06d80-aaf0-11ea-9c92-cac71bfcb0f7.png)

results in the following stack trace:
```
Environment:


Request Method: GET
Request URL: http://<URL>/organizations/1/cluster_types/ericdill-0a89fe2e-6

Django Version: 3.0.7
Python Version: 3.8.2
Installed Applications:
['whitenoise.runserver_nostatic',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.github',
 'bootstrap4',
 'channels',
 'dj_rest_auth',
 'rest_framework',
 'rest_framework.authtoken',
 'sass_processor',
 'api.apps.ApiConfig',
 'resources.apps.ResourcesConfig',
 'users.apps.UsersConfig',
 'cc',
 'clusters']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/conda/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/conda/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "./users/views.py", line 142, in get_context_data
    context["clusters"] = ClusterQuerySet(
  File "./resources/models/aws.py", line 68, in __init__
    response = ResourcesConfig.backend.list_dask_clusters(self.organization)

Exception Type: AttributeError at /organizations/1/cluster_types/ericdill-0a89fe2e-6
Exception Value: 'ClusterManager' object has no attribute 'list_dask_clusters'
```

This is running off of the deployment-dtn branch plus the local changes that you already know about

**Comment by shughes-uk** [comment]
no longer an issue
