### ISSUE TITLE
Workers failing to start

### ISSUE THREAD

**Issue by fjetter** [coiled/feedback#189]
I get some workers that fail to start with a 502 Bad Gateway error during dask preload setup

```
{"msg":"Error running docker","data":{"error":"Creating tmp_worker_1 ... 
Creating tmp_worker_1 ... done
Attaching to tmp_worker_1
distributed.preloading - INFO - Downloading preload at https://cloud.coiled.io/api/v2/cluster_facing/preload/worker
Traceback (most recent call last):
  File \"/opt/conda/lib/python3.9/runpy.py\", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File \"/opt/conda/lib/python3.9/runpy.py\", line 87, in _run_code
    exec(code, run_globals)
  File \"/opt/conda/lib/python3.9/site-packages/distributed/cli/dask_spec.py\", line 43, in <module>
    main()
  File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 1134, in __call__
    return self.main(*args, **kwargs)
  File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 1059, in main
    rv = self.invoke(ctx)
  File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 767, in invoke
    return __callback(*args, **kwargs)
  File \"/opt/conda/lib/python3.9/site-packages/distributed/cli/dask_spec.py\", line 39, in main
    asyncio.get_event_loop().run_until_complete(run())
  File \"/opt/conda/lib/python3.9/asyncio/base_events.py\", line 647, in run_until_complete
    return future.result()
  File \"/opt/conda/lib/python3.9/site-packages/distributed/cli/dask_spec.py\", line 33, in run
    servers = await run_spec(_spec, *args)
  File \"/opt/conda/lib/python3.9/site-packages/distributed/deploy/spec.py\", line 633, in run_spec
    workers[k] = cls(*args, **d.get(\"opts\", {}))
  File \"/opt/conda/lib/python3.9/site-packages/distributed/nanny.py\", line 155, in __init__
    self.preloads = preloading.process_preloads(
  File \"/opt/conda/lib/python3.9/site-packages/distributed/preloading.py\", line 224, in process_preloads
    return [
  File \"/opt/conda/lib/python3.9/site-packages/distributed/preloading.py\", line 225, in <listcomp>
    Preload(dask_server, p, argv, file_dir)
  File \"/opt/conda/lib/python3.9/site-packages/distributed/preloading.py\", line 171, in __init__
    self.module = _download_module(name)
  File \"/opt/conda/lib/python3.9/site-packages/distributed/preloading.py\", line 131, in _download_module
    response = urllib.request.urlopen(request)
  File \"/opt/conda/lib/python3.9/urllib/request.py\", line 214, in urlopen
    return opener.open(url, data, timeout)
  File \"/opt/conda/lib/python3.9/urllib/request.py\", line 523, in open
    response = meth(req, response)
  File \"/opt/conda/lib/python3.9/urllib/request.py\", line 632, in http_response
    response = self.parent.error(
  File \"/opt/conda/lib/python3.9/urllib/request.py\", line 561, in error
    return self._call_chain(*args)
  File \"/opt/conda/lib/python3.9/urllib/request.py\", line 494, in _call_chain
    result = func(*args)
  File \"/opt/conda/lib/python3.9/urllib/request.py\", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
tmp_worker_1 exited with code 1
1
Aborting on container exit...
"}
```

cc @ntabris @shughes-uk 

https://cloud.coiled.io/dask-engineering/clusters/52358/details

**Comment by ntabris** [comment]
This code is already supposed to be retrying on 502: https://github.com/dask/distributed/blob/cb45c610c4aee79f2f0f838da8185c11ea2f387d/distributed/preloading.py#L138

But judging from log timestamps maybe that didn't happen. I would expect to see more time pass between `Creating tmp_worker_1` and the traceback if it had been retrying w/ backoffs.

```
Aug 18 12:47:28 ip-10-0-3-6 cloud-init[1128]: Creating tmp_worker_1 ... done
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]: Attaching to tmp_worker_1
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]: distributed.preloading - INFO - Downloading preload at https://cloud.coiled.io/api/v2/cluster_facing/preload/worker
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]: Traceback (most recent call last):
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     return _run_code(code, main_globals, None,
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     exec(code, run_globals)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/site-packages/distributed/cli/dask_spec.py", line 43, in <module>
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     main()
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1134, in __call__
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     return self.main(*args, **kwargs)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1059, in main
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     rv = self.invoke(ctx)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1401, in invoke
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     return ctx.invoke(self.callback, **ctx.params)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 767, in invoke
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     return __callback(*args, **kwargs)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/site-packages/distributed/cli/dask_spec.py", line 39, in main
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     asyncio.get_event_loop().run_until_complete(run())
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     return future.result()
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/site-packages/distributed/cli/dask_spec.py", line 33, in run
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     servers = await run_spec(_spec, *args)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/site-packages/distributed/deploy/spec.py", line 633, in run_spec
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     workers[k] = cls(*args, **d.get("opts", {}))
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/site-packages/distributed/nanny.py", line 155, in __init__
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     self.preloads = preloading.process_preloads(
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/site-packages/distributed/preloading.py", line 224, in process_preloads
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     return [
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/site-packages/distributed/preloading.py", line 225, in <listcomp>
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     Preload(dask_server, p, argv, file_dir)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/site-packages/distributed/preloading.py", line 171, in __init__
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     self.module = _download_module(name)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/site-packages/distributed/preloading.py", line 131, in _download_module
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     response = urllib.request.urlopen(request)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/urllib/request.py", line 214, in urlopen
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     return opener.open(url, data, timeout)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/urllib/request.py", line 523, in open
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     response = meth(req, response)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/urllib/request.py", line 632, in http_response
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     response = self.parent.error(
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/urllib/request.py", line 561, in error
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     return self._call_chain(*args)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/urllib/request.py", line 494, in _call_chain
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     result = func(*args)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:   File "/opt/conda/lib/python3.9/urllib/request.py", line 641, in http_error_default
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
Aug 18 12:47:29 ip-10-0-3-6 cloud-init[1128]: urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```
