### ISSUE TITLE
Hitting issue launching a cluster since account name has an underscore in it

### ISSUE THREAD

**Issue by amrobbins** [coiled/feedback#244]
Hi,

I'm trying to spin up a dask cluster, when I tried to set it up I used account named micah_cart and this resulted in an error trying to spin up a cluster:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/root/sales_forecasting_venv/lib/python3.8/site-packages/coiled/_beta/cluster.py", line 585, in init
    raise e.with_traceback(None)
coiled.errors.ClusterCreationError: Cluster status is error (reason: Infrastructure failed to create (reason: 400 POST https://compute.googleapis.com/compute/v1/projects/ml-ops-370718/global/firewalls?requestId=7a058266-ede7-5ec0-b32a-5db1447f9d1b: Invalid value for field '[resource.name](http://resource.name/)': 'coiled-dask-micah_c7b-228879-egress'. Must be a match of regex '(?:a-z?)')) (cluster_id: 228879)

So this is blocking me from getting dask set up. I could instead try to use my account name andrew-robbins which conforms to the naming rules, but when I try to set this up new it is still picking up micah_cart. Is there something I can delete so that I can start fresh? Or maybe since micah set up this coiled account it is defaulting to his user name?

**Comment by ntabris** [comment]
I've emailed about this and will prioritize getting a fix.

**Comment by dchudz** [comment]
Hi @amrobbins! Sorry about this. 

Nat's fixing the underscore issue.

In the meantime, if you want (as `andrew-robbins`) to not use the `micah_cart` account, you change your default account to `andrew-robbins` in the profile settings. 

Here's what it looks like for me:

<img width="267" alt="Screen Shot 2023-06-13 at 4 20 25 PM" src="https://github.com/coiled/feedback/assets/1222726/b6b60f08-762d-45ae-89b6-cf04d547f996">


<img width="775" alt="Screen Shot 2023-06-13 at 4 18 47 PM" src="https://github.com/coiled/feedback/assets/1222726/8c7abd27-234a-40e0-9b6f-bb13ce95dcd1">

Note that you (andrew-robbins) are currently not a member of the `micah_cart` anymore (maybe Micah removed you because of the underscore problem?), so if you want that to work after the underscore problem is fixed, you'll need to be added back to that account.

**Comment by ntabris** [comment]
The fix (or hopefully-a-fix since I wasn't able to replicate the issue) has now been deployed to prod, if you could give the `micah_cart` account a try again and see if that works, that would be great!
