### ISSUE TITLE
Error when uploading conda environment with new packages

### ISSUE THREAD

**Issue by mmccarty** [coiled/feedback#26]
This one might be an edge or I'm doing it wrong. I'm trying to add conda packages to my local environment and then upload it to coiled.

```
(coiled-mmccarty-dask-ml) mikes-mbp:~ mmccarty$ conda install -c conda-forge xarray datashader -y
Collecting package metadata (current_repodata.json): done
Solving environment: -
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::s3fs==0.4.2=py_0
  - conda-forge/osx-64::s3transfer==0.3.3=py38h32f6830_1
  - conda-forge/noarch::boto3==1.14.26=pyh9f0ad1d_0
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::s3fs==0.4.2=py_0
  - conda-forge/osx-64::s3transfer==0.3.3=py38h32f6830_1
  - conda-forge/noarch::boto3==1.14.26=pyh9f0ad1d_0
done

## Package Plan ##

  environment location: /Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml

  added / updated specs:
    - datashader
    - xarray


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    datashader-0.10.0          |             py_0        14.0 MB  conda-forge
    param-1.9.3                |             py_0          60 KB  conda-forge
    pyct-0.4.6                 |             py_0           3 KB  conda-forge
    pyct-core-0.4.6            |             py_0          13 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        14.0 MB

The following NEW packages will be INSTALLED:

  blosc              conda-forge/osx-64::blosc-1.19.0-h4a8c4bd_0
  botocore           conda-forge/noarch::botocore-1.17.26-pyh9f0ad1d_0
  brotli             conda-forge/osx-64::brotli-1.0.7-h4a8c4bd_1004
  brunsli            conda-forge/osx-64::brunsli-0.1-h4a8c4bd_0
  bzip2              conda-forge/osx-64::bzip2-1.0.8-h0b31af3_2
  charls             conda-forge/osx-64::charls-2.1.0-h4a8c4bd_2
  colorcet           conda-forge/noarch::colorcet-2.0.1-py_0
  cycler             conda-forge/noarch::cycler-0.10.0-py_2
  datashader         conda-forge/noarch::datashader-0.10.0-py_0
  datashape          conda-forge/noarch::datashape-0.5.4-py_1
  giflib             conda-forge/osx-64::giflib-5.2.1-h0b31af3_2
  imagecodecs        conda-forge/osx-64::imagecodecs-2020.5.30-py38h197531b_2
  imageio            conda-forge/noarch::imageio-2.9.0-py_0
  jxrlib             conda-forge/osx-64::jxrlib-1.1-h0b31af3_2
  kiwisolver         conda-forge/osx-64::kiwisolver-1.2.0-py38ha0d09dd_0
  lerc               conda-forge/osx-64::lerc-2.2-h4a8c4bd_0
  libaec             conda-forge/osx-64::libaec-1.0.4-h4a8c4bd_1
  libzopfli          conda-forge/osx-64::libzopfli-1.0.3-h4a8c4bd_0
  matplotlib-base    conda-forge/osx-64::matplotlib-base-3.3.0-py38haed9462_1
  networkx           conda-forge/noarch::networkx-2.4-py_1
  openjpeg           conda-forge/osx-64::openjpeg-2.3.1-h254dc36_3
  param              conda-forge/noarch::param-1.9.3-py_0
  pyct               conda-forge/noarch::pyct-0.4.6-py_0
  pyct-core          conda-forge/noarch::pyct-core-0.4.6-py_0
  pywavelets         conda-forge/osx-64::pywavelets-1.1.1-py38h65ad66c_1
  scikit-image       conda-forge/osx-64::scikit-image-0.17.2-py38h5fc983b_1
  snappy             conda-forge/osx-64::snappy-1.1.8-h4a8c4bd_3
  tifffile           conda-forge/noarch::tifffile-2020.7.17-py_0
  xarray             conda-forge/noarch::xarray-0.16.0-py_0
  zfp                conda-forge/osx-64::zfp-0.5.5-h4a8c4bd_1



Downloading and Extracting Packages
datashader-0.10.0    | 14.0 MB   | ############################################################################################################################################################# | 100%
pyct-0.4.6           | 3 KB      | ############################################################################################################################################################# | 100%
param-1.9.3          | 60 KB     | ############################################################################################################################################################# | 100%
pyct-core-0.4.6      | 13 KB     | ############################################################################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(coiled-mmccarty-dask-ml) mikes-mbp:~ mmccarty$ conda install -c pyviz holoviews bokeh -y
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml

  added / updated specs:
    - bokeh
    - holoviews


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    matplotlib-3.3.0           |                1           6 KB  conda-forge
    pyviz_comms-0.7.6          |             py_0          11 KB  pyviz
    tqdm-4.48.0                |     pyh9f0ad1d_0          52 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          69 KB

The following NEW packages will be INSTALLED:

  holoviews          pyviz/noarch::holoviews-1.13.3-py_0
  markdown           conda-forge/noarch::markdown-3.2.2-py_0
  matplotlib         conda-forge/osx-64::matplotlib-3.3.0-1
  panel              pyviz/noarch::panel-0.9.7-py_0
  pyviz_comms        pyviz/noarch::pyviz_comms-0.7.6-py_0
  tqdm               conda-forge/noarch::tqdm-4.48.0-pyh9f0ad1d_0



Downloading and Extracting Packages
pyviz_comms-0.7.6    | 11 KB     | ############################################################################################################################################################# | 100%
tqdm-4.48.0          | 52 KB     | ############################################################################################################################################################# | 100%
matplotlib-3.3.0     | 6 KB      | ############################################################################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(coiled-mmccarty-dask-ml) mikes-mbp:~ mmccarty$ coiled upload
Creating Coiled software environment from local coiled-mmccarty-dask-ml conda environment
Updating Software Environment ... -
Solving conda environment... /
Failed:


Traceback (most recent call last):
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/bin/coiled", line 8, in <module>
    sys.exit(cli())
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/lib/python3.8/site-packages/coiled/cli/upload.py", line 46, in upload
    create_software_environment(name=name, conda=spec)
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/lib/python3.8/site-packages/coiled/core.py", line 711, in create_software_environment
    return cloud.create_software_environment(
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/lib/python3.8/site-packages/coiled/core.py", line 433, in create_software_environment
    return self._sync(
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/lib/python3.8/site-packages/coiled/core.py", line 274, in _sync
    return sync(
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/lib/python3.8/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/mmccarty/miniconda3/envs/coiled-mmccarty-dask-ml/lib/python3.8/site-packages/coiled/core.py", line 495, in _create_software_environment
    raise ValueError(
ValueError: Unable to update Environment:


  - libgfortran=4.0.0
```

**Comment by necaris** [comment]
could you paste the `conda env export` output? I wonder if this might be something that's platform dependent :-(

**Comment by mmccarty** [comment]
Sure!

```
(coiled-mmccarty-dask-ml) mikes-mbp:~ mmccarty$ conda env export
name: coiled-mmccarty-dask-ml
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - aiohttp=3.6.2=py38h0b31af3_0
  - appnope=0.1.0=py38h32f6830_1001
  - async-timeout=3.0.1=py_1000
  - attrs=19.3.0=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - bleach=3.1.5=pyh9f0ad1d_0
  - blosc=1.19.0=h4a8c4bd_0
  - bokeh=2.1.1=py38h32f6830_0
  - boto3=1.14.26=pyh9f0ad1d_0
  - brotli=1.0.7=h4a8c4bd_1004
  - brotlipy=0.7.0=py38h64e0658_1000
  - brunsli=0.1=h4a8c4bd_0
  - bzip2=1.0.8=h0b31af3_2
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py38h32f6830_0
  - cffi=1.14.0=py38h356ff06_0
  - chardet=3.0.4=py38h32f6830_1006
  - charls=2.1.0=h4a8c4bd_2
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=1.5.0=py_0
  - colorcet=2.0.1=py_0
  - cryptography=3.0=py38h52adbb4_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py38h0b31af3_0
  - dask=2.21.0=py_0
  - dask-core=2.21.0=py_0
  - dask-glm=0.2.0=py_1
  - dask-labextension=2.0.2=py_0
  - dask-ml=1.5.0=py_0
  - dask-xgboost=0.1.10=py_0
  - datashader=0.10.0=py_0
  - datashape=0.5.4=py_1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.21.0=py38h32f6830_0
  - docutils=0.15.2=py38_0
  - entrypoints=0.3=py38h32f6830_1001
  - freetype=2.10.2=h8da9a1a_0
  - fsspec=0.7.4=py_0
  - giflib=5.2.1=h0b31af3_2
  - heapdict=1.0.1=py_0
  - holoviews=1.13.3=py_0
  - icu=67.1=h4a8c4bd_0
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2020.5.30=py38h197531b_2
  - imageio=2.9.0=py_0
  - importlib-metadata=1.7.0=py38h32f6830_0
  - importlib_metadata=1.7.0=0
  - ipykernel=5.3.4=py38h23f93f0_0
  - ipython=7.16.1=py38h23f93f0_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.2=py38h32f6830_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=0.16.0=py_0
  - jpeg=9d=h0b31af3_0
  - json5=0.9.4=pyh9f0ad1d_0
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter-server-proxy=1.5.0=py_0
  - jupyter_client=6.1.6=py_0
  - jupyter_core=4.6.3=py38h32f6830_1
  - jupyterlab=2.2.0=py_0
  - jupyterlab_server=1.2.0=py_0
  - jxrlib=1.1=h0b31af3_2
  - kiwisolver=1.2.0=py38ha0d09dd_0
  - lcms2=2.11=h174193d_0
  - lerc=2.2=h4a8c4bd_0
  - libaec=1.0.4=h4a8c4bd_1
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcxx=10.0.0=h1af66ff_2
  - libffi=3.2.1=h4a8c4bd_1007
  - libgfortran=4.0.0=2
  - liblapack=3.8.0=17_openblas
  - libllvm9=9.0.1=h7475705_1
  - libopenblas=0.3.10=openmp_h63d9170_3
  - libpng=1.6.37=hbbe82c9_1
  - libsodium=1.0.17=h01d97ff_0
  - libtiff=4.1.0=h2ae36a8_6
  - libuv=1.38.0=h0b31af3_0
  - libwebp-base=1.1.0=h0b31af3_3
  - libxgboost=0.90=h4a8c4bd_4
  - libzopfli=1.0.3=h4a8c4bd_0
  - llvm-openmp=10.0.1=h28b9765_0
  - llvmlite=0.33.0=py38h3707e27_1
  - locket=0.2.0=py_2
  - lz4-c=1.9.2=h4a8c4bd_1
  - markdown=3.2.2=py_0
  - markupsafe=1.1.1=py38h64e0658_1
  - matplotlib=3.3.0=1
  - matplotlib-base=3.3.0=py38haed9462_1
  - mistune=0.8.4=py38h64e0658_1001
  - msgpack-python=1.0.0=py38ha0d09dd_1
  - multipledispatch=0.6.0=py_0
  - nbconvert=5.6.1=py38h32f6830_1
  - nbformat=5.0.7=py_0
  - ncurses=6.2=hb1e8313_1
  - networkx=2.4=py_1
  - nodejs=14.6.0=hdde0ff8_0
  - notebook=6.0.3=py38h32f6830_1
  - numba=0.50.1=py38h9529b5f_1
  - numpy=1.19.0=py38h598c1e0_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h254dc36_3
  - openssl=1.1.1g=h0b31af3_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.5=py38h5fc983b_0
  - pandoc=2.10=h1de35cc_0
  - pandocfilters=1.4.2=py_1
  - panel=0.9.7=py_0
  - param=1.9.3=py_0
  - parso=0.7.0=pyh9f0ad1d_0
  - partd=1.1.0=py_0
  - pexpect=4.8.0=py38h32f6830_1
  - pickleshare=0.7.5=py38h32f6830_1001
  - pillow=7.2.0=py38h83dc5e5_1
  - pip=20.1.1=py_1
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_1
  - psutil=5.7.2=py38h4d0b108_0
  - ptyprocess=0.6.0=py_1001
  - py-xgboost=0.90=py38_4
  - pycparser=2.20=pyh9f0ad1d_2
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.16.0=py38h64e0658_0
  - pysocks=1.7.1=py38h32f6830_1
  - python=3.8.5=cpython_h85f3143_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=pyh9f0ad1d_0
  - pyviz_comms=0.7.6=py_0
  - pywavelets=1.1.1=py38h65ad66c_1
  - pyyaml=5.3.1=py38h64e0658_0
  - readline=8.0=h0678c8f_2
  - requests=2.24.0=pyh9f0ad1d_0
  - s3fs=0.4.2=py_0
  - s3transfer=0.3.3=py38h32f6830_1
  - scikit-image=0.17.2=py38h5fc983b_1
  - scikit-learn=0.23.1=py38hb7f0800_0
  - scipy=1.5.1=py38h38b60c6_0
  - send2trash=1.5.0=py_0
  - setuptools=49.2.0=py38h32f6830_0
  - simpervisor=0.3=py_1
  - six=1.15.0=pyh9f0ad1d_0
  - snappy=1.1.8=h4a8c4bd_3
  - sortedcontainers=2.2.2=pyh9f0ad1d_0
  - sqlite=3.32.3=h93121df_1
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py38h32f6830_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2020.7.17=py_0
  - tk=8.6.10=hbbe82c9_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py38h64e0658_1
  - tqdm=4.48.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py38h32f6830_1
  - typing_extensions=3.7.4.2=py_0
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - xarray=0.16.0=py_0
  - xgboost=0.90=py38h4a8c4bd_4
  - xz=5.2.5=h0b31af3_1
  - yaml=0.2.5=h0b31af3_0
  - zeromq=4.3.2=h6de7cb9_2
  - zfp=0.5.5=h4a8c4bd_1
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h0b31af3_1006
  - zstd=1.4.5=h0384e3a_1
  - pip:
    - aiobotocore==1.0.7
    - aioitertools==0.7.0
    - botocore==1.15.32
    - coiled==0.0.15
    - ipython-genutils==0.2.0
    - multidict==4.7.6
    - pyzmq==19.0.1
    - wrapt==1.12.1
    - yarl==1.4.2
```

**Comment by necaris** [comment]
I do get a solving failure when I try to import this environment on my local machine (Linux) -- will try again to reproduce later today. /cc @jrbourbeau in case something here leaps out at you :-)
```
❯ conda env create -f mikes-env.yml 
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound: 
  - lerc==2.2=h4a8c4bd_0
  - libopenblas==0.3.10=openmp_h63d9170_3
  - zstd==1.4.5=h0384e3a_1
  - cffi==1.14.0=py38h356ff06_0
  - pyrsistent==0.16.0=py38h64e0658_0
  - libsodium==1.0.17=h01d97ff_0
  - xgboost==0.90=py38h4a8c4bd_4
  - charls==2.1.0=h4a8c4bd_2
  - libffi==3.2.1=h4a8c4bd_1007
  - kiwisolver==1.2.0=py38ha0d09dd_0
  - libaec==1.0.4=h4a8c4bd_1
  - lcms2==2.11=h174193d_0
  - llvmlite==0.33.0=py38h3707e27_1
  - imagecodecs==2020.5.30=py38h197531b_2
  - tornado==6.0.4=py38h64e0658_1
  - psutil==5.7.2=py38h4d0b108_0
  - freetype==2.10.2=h8da9a1a_0
  - ncurses==6.2=hb1e8313_1
  - libzopfli==1.0.3=h4a8c4bd_0
  - scikit-learn==0.23.1=py38hb7f0800_0
  - jxrlib==1.1=h0b31af3_2
  - xz==5.2.5=h0b31af3_1
  - blosc==1.19.0=h4a8c4bd_0
  - icu==67.1=h4a8c4bd_0
  - markupsafe==1.1.1=py38h64e0658_1
  - pywavelets==1.1.1=py38h65ad66c_1
  - numpy==1.19.0=py38h598c1e0_0
  - libwebp-base==1.1.0=h0b31af3_3
  - brotlipy==0.7.0=py38h64e0658_1000
  - mistune==0.8.4=py38h64e0658_1001
  - scipy==1.5.1=py38h38b60c6_0
  - libpng==1.6.37=hbbe82c9_1
  - yaml==0.2.5=h0b31af3_0
  - libgfortran==4.0.0=2
  - matplotlib-base==3.3.0=py38haed9462_1
  - pandas==1.0.5=py38h5fc983b_0
  - jpeg==9d=h0b31af3_0
  - nodejs==14.6.0=hdde0ff8_0
  - brunsli==0.1=h4a8c4bd_0
  - llvm-openmp==10.0.1=h28b9765_0
  - giflib==5.2.1=h0b31af3_2
  - lz4-c==1.9.2=h4a8c4bd_1
  - bzip2==1.0.8=h0b31af3_2
  - libuv==1.38.0=h0b31af3_0
  - tk==8.6.10=hbbe82c9_0
  - appnope==0.1.0=py38h32f6830_1001
  - readline==8.0=h0678c8f_2
  - scikit-image==0.17.2=py38h5fc983b_1
  - msgpack-python==1.0.0=py38ha0d09dd_1
  - numba==0.50.1=py38h9529b5f_1
  - openssl==1.1.1g=h0b31af3_0
  - aiohttp==3.6.2=py38h0b31af3_0
  - zfp==0.5.5=h4a8c4bd_1
  - pandoc==2.10=h1de35cc_0
  - cryptography==3.0=py38h52adbb4_0
  - libcxx==10.0.0=h1af66ff_2
  - cytoolz==0.10.1=py38h0b31af3_0
  - pillow==7.2.0=py38h83dc5e5_1
  - snappy==1.1.8=h4a8c4bd_3
  - zlib==1.2.11=h0b31af3_1006
  - pyyaml==5.3.1=py38h64e0658_0
  - python==3.8.5=cpython_h85f3143_0
  - libllvm9==9.0.1=h7475705_1
  - brotli==1.0.7=h4a8c4bd_1004
  - sqlite==3.32.3=h93121df_1
  - libtiff==4.1.0=h2ae36a8_6
  - zeromq==4.3.2=h6de7cb9_2
  - libxgboost==0.90=h4a8c4bd_4
  - openjpeg==2.3.1=h254dc36_3
```

**Comment by mmccarty** [comment]
Thanks @necaris ! No rush at all. The work around is to just create a new environment, but I wanted to report it.

**Comment by jrbourbeau** [comment]
@mmccarty when you get a chance could you give the output of `conda env export --from-history`?

**Comment by shughes-uk** [comment]
Package sync renders this redundant
