### ISSUE TITLE
Coiled notebook failing with "AWS was not able to validate the provided access credentials"

### ISSUE THREAD

**Issue by rsignell** [coiled/feedback#280]
I'm trying to start a Coiled notebook in the `esip-lab` workspace thusly:
```
 coiled notebook start --region us-west-2 --vm-type m5.2xlarge --software pangeo --name streamjoy --workspace esip-lab
``` 
and getting back:
``` 
Traceback (most recent call last):
  File "/home/rsignell/miniforge3/envs/pangeo/bin/coiled", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/rsignell/miniforge3/envs/pangeo/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsignell/miniforge3/envs/pangeo/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/rsignell/miniforge3/envs/pangeo/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsignell/miniforge3/envs/pangeo/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsignell/miniforge3/envs/pangeo/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsignell/miniforge3/envs/pangeo/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsignell/miniforge3/envs/pangeo/lib/python3.11/site-packages/coiled/cli/notebook/notebook.py", line 221, in start_notebook
    _start_notebook(
  File "/home/rsignell/miniforge3/envs/pangeo/lib/python3.11/site-packages/coiled/cli/notebook/notebook.py", line 446, in _start_notebook
    raise e
  File "/home/rsignell/miniforge3/envs/pangeo/lib/python3.11/site-packages/coiled/cli/notebook/notebook.py", line 310, in _start_notebook
    cluster = coiled.Cluster(
              ^^^^^^^^^^^^^^^
  File "/home/rsignell/miniforge3/envs/pangeo/lib/python3.11/site-packages/coiled/v2/cluster.py", line 731, in __init__
    raise e.with_traceback(None)  # noqa: B904
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
coiled.errors.ClusterCreationError: Cluster status is error (reason: Infrastructure failed to create (reason: AWS was not able to validate the provided access credentials)) (cluster_id: 458744)
```
I thought maybe something was out of date, so tried this update command without really understanding what I was doing:
![image](https://github.com/coiled/feedback/assets/125569335/04234c28-6067-4134-9702-42b5ae74540c)

I wasn't sure what to try next...

**Comment by dchudz** [comment]
Hey Rich, I'd be happy to try to remind us of some things about the `esip-lab` workspace (who set it up and what we might try next), but probably not in a public issue. Maybe email support@coiled.io?

**Comment by dchudz** [comment]
(Emailed separately.)
