### ISSUE TITLE
Certain worker output texts break logging retrieval

### ISSUE THREAD

**Issue by bmdnetrias** [coiled/feedback#306]
I'm running Hugging Face transformer training on coiled and the processing is going well. The `transformers.trainer` code emits a log message with a bracket that triggers an exception in `rich` when I try to retrieve logs from coiled. I think disabling the `transformers.trainer` logger, which I can do on my side, should relieve the problem.

Here's an example of the log line:

```
2024-12-03 16:44:16.3640 10.0.22.158 INFO   |     703|1:04:46.243157|2024-12-03 21:44:16+00:00|transformers.trainer|_rotate_checkpoints|Deleting older checkpoint [/tmp/hops_app_dir/training/models/mambauser_4d3a0c5ce1974eec9a8b09e37cedffae/checkpoint-3500] due to args.save_total_limit
```

And the subsequent exception.

```
(hops) bmdnetrias@bmdnetrias:~/experiments/coiled-slurm$ coiled logs 675635 --no-scheduler --no-color  --label none --since 3m --tail > foo.txt
Traceback (most recent call last):
  File "/Users/bmdnetrias/.pyenv/versions/hops/bin/coiled", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/bmdnetrias/.pyenv/versions/3.11.9/envs/hops/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmdnetrias/.pyenv/versions/3.11.9/envs/hops/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/bmdnetrias/.pyenv/versions/3.11.9/envs/hops/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmdnetrias/.pyenv/versions/3.11.9/envs/hops/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmdnetrias/.pyenv/versions/3.11.9/envs/hops/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmdnetrias/.pyenv/versions/3.11.9/envs/hops/lib/python3.11/site-packages/coiled/cli/cluster/better_logs.py", line 172, in better_logs_cli
    better_logs(
  File "/Users/bmdnetrias/.pyenv/versions/3.11.9/envs/hops/lib/python3.11/site-packages/coiled/cli/cluster/better_logs.py", line 300, in better_logs
    print_events(
  File "/Users/bmdnetrias/.pyenv/versions/3.11.9/envs/hops/lib/python3.11/site-packages/coiled/cli/cluster/better_logs.py", line 376, in print_events
    console.print(
  File "/Users/bmdnetrias/.pyenv/versions/3.11.9/envs/hops/lib/python3.11/site-packages/rich/console.py", line 1684, in print
    renderables = self._collect_renderables(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmdnetrias/.pyenv/versions/3.11.9/envs/hops/lib/python3.11/site-packages/rich/console.py", line 1544, in _collect_renderables
    self.render_str(
  File "/Users/bmdnetrias/.pyenv/versions/3.11.9/envs/hops/lib/python3.11/site-packages/rich/console.py", line 1434, in render_str
    rich_text = render_markup(
                ^^^^^^^^^^^^^^
  File "/Users/bmdnetrias/.pyenv/versions/3.11.9/envs/hops/lib/python3.11/site-packages/rich/markup.py", line 167, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[/tmp/hops_app_dir/training/models/mambauser_4cde0eb393bf4bf9af0d991a048a8650/checkpoint-3500]' at position 125 doesn't match any open tag
```

Thinking out loud, a command line option for log retrieval that skips/disables the `rich` rendering and just transmits the raw logs would be useful for my workload. Point me in the right direction if I'm missing something obvious.

**Comment by bmdnetrias** [comment]
I'm probably an outlier at the moment, but I'm focused on using coiled for batch workloads and have some pretty bespoke logging mechanisms. At the end of the day I'd like to cycle back after a run completes and faithfully get back the log output that I would see if the batch ran on my laptop. This is for post-processing and forensic investigations of code execution.

Interleaving `rich` and normal printing is probably fine for interactive retrieval by humans at the CLI. Probably not so much for the case described above where log message consistency is paramount.

Having said all of that, I'm building up an orthogonal component of my code that logs to a file on the VM and then pushes the file into cloud storage as an artifact after batch completion. That should solve my use case without ya'll having to alter the product much.

**Comment by jrbourbeau** [comment]
Just following up here -- the `coiled=1.67.0` release (out a few minutes ago) adds the `--no-color` flag

**Comment by bmdnetrias** [comment]
A quick check from this end and all seems well. Thanks for the quick response. Closing.
