### ISSUE TITLE
Exception when creating pip environment that uses `--extra-index-url`

### ISSUE THREAD

**Issue by jacobtomlinson** [coiled/feedback#309]
I have a requirements file that sets an extra package index url. This is a valid `requirements.txt` and I can successfully install it with `pip install -r requirements.txt`.

```
--extra-index-url=https://pypi.nvidia.com
cudf-cu12==24.10.*
pandas
s3fs
```

However when I try and create a Coiled environment via the CLI it fails.

```pytb
coiled env create --name rapids-2410-cudf-only --pip /tmp/cudf_requirements.txt
Traceback (most recent call last):
  File "/Users/jtomlinson/miniconda3/envs/dask/bin/coiled", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/cli/env.py", line 122, in create
    create_software_environment(
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/core.py", line 2270, in create_software_environment
    return cloud.create_software_environment(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/core.py", line 812, in create_software_environment
    return self._sync(
           ^^^^^^^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/core.py", line 561, in _sync
    return cast(_T, sync(self.loop, func, *args, callback_timeout=None, **kwargs))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/distributed/utils.py", line 434, in sync
    raise error
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/distributed/utils.py", line 408, in f
    result = yield future
             ^^^^^^^^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/context.py", line 112, in async_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/core.py", line 870, in _create_software_environment
    senv = await create_env_spec(conda=conda, pip=pip)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/software.py", line 167, in create_env_spec
    raw_index_urls = [
                     ^
  File "/Users/jtomlinson/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/software.py", line 168, in <listcomp>
    line.strip().split()[1]
    ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

```console
$ coiled --version
1.67.0
```

**Comment by jacobtomlinson** [comment]
Same in Python.

```python
In [1]: import coiled
   ...:
   ...: # Create software environment
   ...: coiled.create_software_environment(
   ...:     name="rapids-2410-cudf-only",
   ...:     pip=["--extra-index-url=https://pypi.nvidia.com", "cudf-cu12==24.10.*", "pandas", "s3fs"],
   ...: )
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[1], line 4
      1 import coiled
      3 # Create software environment
----> 4 coiled.create_software_environment(
      5     name="rapids-2410-cudf-only",
      6     pip=["--extra-index-url=https://pypi.nvidia.com", "cudf-cu12==24.10.*", "pandas", "s3fs"],
      7 )

File ~/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/core.py:2270, in create_software_environment(name, account, workspace, conda, pip, container, log_output, force_rebuild, use_entrypoint, gpu_enabled, arm, architecture, region_name, include_local_code, ignore_local_packages, use_uv_installer)
   2268 with Cloud() as cloud:
   2269     try:
-> 2270         return cloud.create_software_environment(
   2271             name=name,
   2272             account=account,
   2273             workspace=workspace,
   2274             conda=conda,
   2275             pip=pip,
   2276             container=container,
   2277             log_output=log_output,
   2278             force_rebuild=force_rebuild,
   2279             use_entrypoint=use_entrypoint,
   2280             gpu_enabled=gpu_enabled,
   2281             arm=arm,
   2282             architecture=architecture,
   2283             region_name=region_name,
   2284             include_local_code=include_local_code,
   2285             ignore_local_packages=ignore_local_packages,
   2286             use_uv_installer=use_uv_installer,
   2287         )
   2288     except Exception as e:
   2289         error = e

File ~/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/core.py:812, in Cloud.create_software_environment(self, name, account, workspace, conda, pip, container, log_output, force_rebuild, use_entrypoint, wait_build, gpu_enabled, architecture, arm, region_name, include_local_code, ignore_local_packages, use_uv_installer)
    788 def create_software_environment(
    789     self: CloudSyncAsync,
    790     name: Optional[str] = None,
   (...)
    810     Optional[SoftwareEnvironmentAlias],
    811 ]:
--> 812     return self._sync(
    813         self._create_software_environment,
    814         name=name,
    815         workspace=workspace or account,
    816         conda=conda,
    817         pip=pip,
    818         container=container,
    819         log_output=log_output,
    820         force_rebuild=force_rebuild,
    821         use_entrypoint=use_entrypoint,
    822         wait_build=wait_build,
    823         gpu_enabled=gpu_enabled,
    824         architecture=ArchitectureTypesEnum.ARM64 if arm else architecture,  # arm bool takes precedence
    825         region_name=region_name,
    826         include_local_code=include_local_code,
    827         ignore_local_packages=ignore_local_packages,
    828         use_uv_installer=use_uv_installer,
    829     )

File ~/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/core.py:561, in Cloud._sync(self, func, *args, **kwargs)
    559     return future
    560 else:
--> 561     return cast(_T, sync(self.loop, func, *args, callback_timeout=None, **kwargs))

File ~/miniconda3/envs/dask/lib/python3.11/site-packages/distributed/utils.py:434, in sync(loop, func, callback_timeout, *args, **kwargs)
    431         wait(10)
    433 if error is not None:
--> 434     raise error
    435 else:
    436     return result

File ~/miniconda3/envs/dask/lib/python3.11/site-packages/distributed/utils.py:408, in sync.<locals>.f()
    406         awaitable = wait_for(awaitable, timeout)
    407     future = asyncio.ensure_future(awaitable)
--> 408     result = yield future
    409 except Exception as exception:
    410     error = exception

File ~/miniconda3/envs/dask/lib/python3.11/site-packages/tornado/gen.py:767, in Runner.run(self)
    765 try:
    766     try:
--> 767         value = future.result()
    768     except Exception as e:
    769         # Save the exception for later. It's important that
    770         # gen.throw() not be called inside this try/except block
    771         # because that makes sys.exc_info behave unexpectedly.
    772         exc: Optional[Exception] = e

File ~/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/context.py:112, in track_context.<locals>.async_wrapper(*args, **kwargs)
    110 trace_context = get_trace_context(func)
    111 with trace_context[0], trace_context[1]:
--> 112     return await func(*args, **kwargs)

File ~/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/core.py:870, in Cloud._create_software_environment(self, name, workspace, conda, pip, container, log_output, force_rebuild, use_entrypoint, wait_build, gpu_enabled, architecture, region_name, include_local_code, ignore_local_packages, use_uv_installer)
    868     raise TypeError("The build backend does not support including local code when using a container")
    869 if conda or pip:
--> 870     senv = await create_env_spec(conda=conda, pip=pip)
    871     if include_local_code:
    872         prefix = await scan_prefix()

File ~/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/software.py:167, in create_env_spec(conda, pip)
    165 else:
    166     spec["raw_pip"].extend(raw_pip)
--> 167 raw_index_urls = [
    168     line.strip().split()[1]
    169     for line in spec["raw_pip"]
    170     if line.startswith("--index-url") or line.startswith("--extra-index-url")
    171 ]
    172 index_urls = get_index_urls()
    173 if index_urls:

File ~/miniconda3/envs/dask/lib/python3.11/site-packages/coiled/software.py:168, in <listcomp>(.0)
    165 else:
    166     spec["raw_pip"].extend(raw_pip)
    167 raw_index_urls = [
--> 168     line.strip().split()[1]
    169     for line in spec["raw_pip"]
    170     if line.startswith("--index-url") or line.startswith("--extra-index-url")
    171 ]
    172 index_urls = get_index_urls()
    173 if index_urls:

IndexError: list index out of range
```

**Comment by dchudz** [comment]
Thanks Jacob! Sorry about this - we'll take a look.

**Comment by dan-blanchard** [comment]
@jacobtomlinson I can get this patched up soon, but in the meantime if you just use `--extra-index-url https://pypi.nvidia.com/` instead of `--extra-index-url=https://pypi.nvidia.com/` (note the space instead of `=`), that should work.

**Comment by jacobtomlinson** [comment]
Awesome thanks both!
