### ISSUE TITLE
post build doesn't work in windows

### ISSUE THREAD

**Issue by mrocklin** [coiled/feedback#48]

**Comment by jrbourbeau** [comment]
Thanks for raising an issue, do you have a traceback you can post?

**Comment by mrocklin** [comment]
Yeah, sorry, operating in a rush.  This is mostly for me to not forget it.

Also for future me `coiled install mrocklin/notebook`

**Comment by mrocklin** [comment]
No traceback, but in true Windows form I do get a pop up window:

C:\Uses\mrock\AppData\Local\temptmpa1071e1t.postbuild

This file does not have an app associated with it for performing this action.  Please install an app or, if one is already installed, create an association in the Default Apps Settings page.

**Comment by mrocklin** [comment]
Running post-build commands
ERROR conda.cli.main_run:execute(31): Subprocess for 'conda run ['C:\\Users\\mrock\\AppData\\Local\\Temp\\tmpa1071e1t.postbuild']' command failed.  (See above for error)
The system cannot execute the specified program.

Created local conda environment for mrocklin/notebook

To activate this environment, use

        conda activate coiled-mrocklin-notebook

**Comment by FabioRosado** [comment]
Could I check if this is still an issue? I've tried to run `coiled install fabiorosado/dask` but the command failed because of the event loop. 

```python
(coiled) C:\Users\FabioRosado>coiled install fabiorosado/dask
Creating local conda environment for fabiorosado/dask
Traceback (most recent call last):
  File "c:\users\fabiorosado\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\fabiorosado\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\FabioRosado\anaconda3\Scripts\coiled.exe\__main__.py", line 7, in <module>
  File "c:\users\fabiorosado\anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\fabiorosado\anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\fabiorosado\anaconda3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\fabiorosado\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\fabiorosado\anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\fabiorosado\anaconda3\lib\site-packages\coiled\cli\install.py", line 78, in install
    cloud._loop_runner.run_sync(
  File "c:\users\fabiorosado\anaconda3\lib\site-packages\distributed\utils.py", line 492, in run_sync
    return sync(self.loop, func, *args, **kwargs)
  File "c:\users\fabiorosado\anaconda3\lib\site-packages\distributed\utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "c:\users\fabiorosado\anaconda3\lib\site-packages\distributed\utils.py", line 324, in f
    result[0] = yield future
  File "c:\users\fabiorosado\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\fabiorosado\anaconda3\lib\site-packages\coiled\cli\install.py", line 115, in create_local_env
    await create_conda_env(name=local_env_name, solved_spec=solved_spec)
  File "c:\users\fabiorosado\anaconda3\lib\site-packages\coiled\cli\install.py", line 178, in create_conda_env
    async for line in run_command_in_subprocess(conda_create_cmd):
  File "c:\users\fabiorosado\anaconda3\lib\site-packages\coiled\utils.py", line 302, in run_command_in_subprocess
    proc = await asyncio.create_subprocess_shell(
  File "c:\users\fabiorosado\anaconda3\lib\asyncio\subprocess.py", line 216, in create_subprocess_shell
    transport, protocol = await loop.subprocess_shell(
  File "c:\users\fabiorosado\anaconda3\lib\asyncio\base_events.py", line 1597, in subprocess_shell
    transport = await self._make_subprocess_transport(
  File "c:\users\fabiorosado\anaconda3\lib\asyncio\base_events.py", line 491, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
```

Just wanted to check with you before closing the issue? 🤔

**Comment by jrbourbeau** [comment]
This _may_ still be an issue. At least we haven't actively resolved it yet, so testing it out with the latest development version of `coiled` would be a good next step when you get a chance

**Comment by shughes-uk** [comment]
post build deprecated
